datasource:
  default: development
  development:
    username: sa
    password: sa
    url: "jdbc:h2: ./database"
  production:
    driver: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
ebean:
  ddl:
    run: true
    generate: true
#    seedSql: seed.sql
